In [1]:
ls- al

ls: -: No such file or directory
ls: al: No such file or directory


In [2]:
ls -al

total 11360
drwxr-xr-x@  9 chengjielin  staff      288 Apr 26 20:25 ./
drwxr-xr-x@ 20 chengjielin  staff      640 Nov 12 14:31 ../
drwxr-xr-x   4 chengjielin  staff      128 Apr 26 20:25 .ipynb_checkpoints/
-rwxr-xr-x@  1 chengjielin  staff  5617630 Aug 25  2016 Combined_News_DJIA.csv*
-rwxr-xr-x@  1 chengjielin  staff   167083 Aug 25  2016 DJIA_table.csv*
-rwxr-xr-x@  1 chengjielin  staff      244 Jun 19  2017 README.md*
-rw-r--r--   1 chengjielin  staff       72 Apr 26 20:25 Untitled.ipynb
-rwxr-xr-x@  1 chengjielin  staff     2140 Nov 12 16:03 baseline.py*
-rw-r--r--   1 chengjielin  staff    15140 Nov 20 10:33 untiltled.ipynb


In [13]:
# %load baseline.py
import numpy as np
import pandas as pd

from nltk.sentiment.vader import SentimentIntensityAnalyzer

from sklearn import svm
from sklearn.model_selection import cross_val_score


def import_data(filename):
	return pd.read_csv(filename, header=0).fillna('').values

def pre_process(data):
	for row in data[0:476]:
		for field in row[2:]:
			if not field == '':
				field = field[1:]	# Remove first 'b'
	print("preprocess")
	#print(data)
	print(data.shape)
	return data

def add_avg_sentiment(data):
	sid = SentimentIntensityAnalyzer()
	avgs = np.empty((len(data),1))
	for i in range(0,len(data)):
		sentiments = []
		for field in data[i][2:]:
			sentiments.append(sid.polarity_scores(field)['compound'])
		avg = float(sum(sentiments))/len(sentiments)
		avgs[i] = avg
	print("avg")
	print(avgs)
	print(avgs.shape)
	return np.append(data, avgs, axis=1)

def divide_train_test(data):
	train = data[:1610]
	test = data[1611:]
	return train, test

def train(data, labels):
	print(data.shape)
	print(labels.shape)
	return svm.SVC(kernel='linear', C=1).fit(data, labels)

def cross_validate(data, labels, clsfr):
	return cross_val_score(clsfr, data, labels, cv=5)

def main():
	data = import_data("Combined_News_DJIA.csv")
	pre_processed = pre_process(data)
	sentiment_included = add_avg_sentiment(pre_processed)
	print("sentiment_include")
	print(sentiment_included.shape)
	train_set, test_set = divide_train_test(sentiment_included)
	print("train_set")
	print(train_set.shape)
	train_labels = train_set[:,1].ravel()
	print("train_labels")
	print(train_labels.shape)
	train_sentiments = train_set[:,27].reshape(len(train_set), 1)
	print("train_sentiments")
	print(train_sentiments.shape)
	test_labels = test_set[:,1].ravel()
	test_sentiments = test_set[:,27].reshape(len(test_set),1)

	clsfr = train(train_sentiments, train_labels.astype('int'))
	print("Training done.")
	results = cross_validate(test_sentiments, test_labels.astype('int'), clsfr)
	print(test_labels.mean())
	print(results)
	print("Avg = " + str(results.mean()))
	print("Cross validation done.")
	clsfr.predict(test_sentiments[:10])print()

if __name__ == "__main__":
	main()

preprocess
(1989, 27)
avg
[[-0.30944 ]
 [-0.12074 ]
 [-0.217556]
 ..., 
 [-0.24054 ]
 [-0.280596]
 [-0.338272]]
(1989, 1)
sentiment_include
(1989, 28)
train_set
(1610, 28)
train_labels
(1610,)
train_sentiments
(1610, 1)
(1610, 1)
(1610,)
Training done.
0.5079365079365079
[ 0.50649351  0.52631579  0.50666667  0.50666667  0.50666667]
Avg = 0.510561859193
Cross validation done.
[1 1 1 1 1 1 1 1 1 1]


In [18]:
# %load baseline.py
import numpy as np
import pandas as pd

from nltk.sentiment.vader import SentimentIntensityAnalyzer

from sklearn import svm
from sklearn.model_selection import cross_val_score


def import_data(filename):
	return pd.read_csv(filename, header=0).fillna('').values

def pre_process(data):
	for row in data[0:476]:
		for field in row[2:]:
			if not field == '':
				field = field[1:]	# Remove first 'b'
	print("preprocess")
	#print(data)
	print(data.shape)
	return data

def add_avg_sentiment(data):
	sid = SentimentIntensityAnalyzer()
	avgs = np.empty((len(data),1))
	for i in range(0,len(data)):
		sentiments = []
		for field in data[i][2:]:
			sentiments.append(sid.polarity_scores(field)['compound'])
		avg = float(sum(sentiments))/len(sentiments)
		avgs[i] = avg
	print("avg")
	print(avgs)
	print(avgs.shape)
	return np.append(data, avgs, axis=1)

def divide_train_test(data):
	train = data[:1610]
	test = data[1611:]
	return train, test

def train(data, labels):
	print(data.shape)
	print(labels.shape)
	return svm.SVC(kernel='linear', C=1).fit(data, labels)

def cross_validate(data, labels, clsfr):
	return cross_val_score(clsfr, data, labels, cv=5)

def main():
	data = import_data("Combined_News_DJIA.csv")
	pre_processed = pre_process(data)
	sentiment_included = add_avg_sentiment(pre_processed)
	print("sentiment_include")
	print(sentiment_included.shape)
	train_set, test_set = divide_train_test(sentiment_included)
	print("train_set")
	print(train_set.shape)
	train_labels = train_set[:,1].ravel()
	print("train_labels")
	print(train_labels.shape)
	train_sentiments = train_set[:,27].reshape(len(train_set), 1)
	print("train_sentiments")
	print(train_sentiments.shape)
	test_labels = test_set[:,1].ravel()
	test_sentiments = test_set[:,27].reshape(len(test_set),1)

	clsfr = train(train_sentiments, train_labels.astype('int'))
	print("Training done.")
	results = cross_validate(test_sentiments, test_labels.astype('int'), clsfr)
	print(test_labels.mean())
	print(results)
	print("Avg = " + str(results.mean()))
	print("Cross validation done.")
	pred=clsfr.predict(train_sentiments)
	print("prediction shape")
	print(pred.shape)
	print(pred)
	print(train_labels[0:10])

if __name__ == "__main__":
	main()

preprocess
(1989, 27)
avg
[[-0.30944 ]
 [-0.12074 ]
 [-0.217556]
 ..., 
 [-0.24054 ]
 [-0.280596]
 [-0.338272]]
(1989, 1)
sentiment_include
(1989, 28)
train_set
(1610, 28)
train_labels
(1610,)
train_sentiments
(1610, 1)
(1610, 1)
(1610,)
Training done.
0.5079365079365079
[ 0.50649351  0.52631579  0.50666667  0.50666667  0.50666667]
Avg = 0.510561859193
Cross validation done.
prediction shape
(1610,)
[1 1 1 ..., 1 1 1]
[0 1 0 0 1 1 0 0 1 1]
