In [ ]:
ls -al

In [1]:
import numpy as np
import pandas as pd

from nltk.sentiment.vader import SentimentIntensityAnalyzer

from sklearn import svm
from sklearn.model_selection import cross_val_score

/Users/chengjielin/tensorflow/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
def import_data(filename):
	return pd.read_csv(filename, header=0).fillna('').values

def pre_process(data):
	for row in data[0:476]:
		for field in row[2:]:
			if not field == '':
				field = field[1:]	# Remove first 'b'
	print("preprocess")
	#print(data)
	print(data.shape)
	return data

def add_avg_sentiment(data):
	sid = SentimentIntensityAnalyzer()
	avgs = np.empty((len(data),1))
	for i in range(0,len(data)):
		sentiments = []
		for field in data[i][2:]:
			sentiments.append(sid.polarity_scores(field)['compound'])
		avg = float(sum(sentiments))/len(sentiments)
		avgs[i] = avg
	print("avg")
	print(avgs)
	print(avgs.shape)
	return np.append(data, avgs, axis=1)

def divide_train_test(data):
	train = data[:1610]
	test = data[1611:]
	return train, test

def train(data, labels):
	print(data.shape)
	print(labels.shape)
	return svm.SVC(kernel='linear', C=1).fit(data, labels)

def cross_validate(data, labels, clsfr):
	return cross_val_score(clsfr, data, labels, cv=5)



In [3]:
price = pd.read_csv("price_data.csv",encoding = "ISO-8859-1")
news = pd.read_csv("news_data.csv",encoding = "ISO-8859-1")

In [4]:
price.head()

id   price   timestamp exchange
0   1  6999.8  1523132235      cex
1   1  6984.1  1523133211      cex
2   1  6984.1  1523133241      cex
3   1  6984.1  1523133272      cex
4   1  6984.1  1523133303      cex

In [ ]:
news.head()

In [5]:
price = price.drop(['id','exchange'], 1)
price=price.sort_values(by=['timestamp'],ascending=False)
price.head()

price   timestamp
6090  8291.4  1524182242
6089  8291.8  1524182212
6088  8277.0  1524182181
6087  8295.2  1524182151
6086  8295.2  1524182120

In [6]:
price=price.sort_values(by=['timestamp'],ascending=True)
price.head()

price   timestamp
0  6999.8  1523132235
1  6984.1  1523133211
2  6984.1  1523133241
3  6984.1  1523133272
4  6984.1  1523133303

In [7]:
price = price.set_index('timestamp').diff(periods=1)
price['timestamp'] = price.index
price = price.reset_index(drop=True)
price.head()

price   timestamp
0    NaN  1523132235
1  -15.7  1523133211
2    0.0  1523133241
3    0.0  1523133272
4    0.0  1523133303

In [ ]:
price.head()

In [ ]:
price.head(30)

In [8]:
price = price[price.price.notnull()]
price.head()

price   timestamp
1  -15.7  1523133211
2    0.0  1523133241
3    0.0  1523133272
4    0.0  1523133303
5    0.0  1523133334

In [9]:
from copy import deepcopy
for index,row in price.iterrows():
    #print(row[1]['price'].dtype)
    a= deepcopy(row['price'])
    if a>=0.0:
        price.set_value(index,'price',int(1))
    else:
        price.set_value(index,'price',int(0))
price.head(30)

price   timestamp
1     0.0  1523133211
2     1.0  1523133241
3     1.0  1523133272
4     1.0  1523133303
5     1.0  1523133334
6     0.0  1523133364
7     0.0  1523133395
8     1.0  1523133425
9     1.0  1523133456
10    1.0  1523133487
11    1.0  1523133518
12    1.0  1523133551
13    1.0  1523133581
14    1.0  1523133611
15    1.0  1523133642
16    1.0  1523133672
17    1.0  1523133703
18    1.0  1523133733
19    1.0  1523133764
20    1.0  1523133794
21    1.0  1523133824
22    1.0  1523133855
23    1.0  1523133885
24    1.0  1523133916
25    1.0  1523133947
26    1.0  1523133978
27    0.0  1523134008
28    1.0  1523134039
29    0.0  1523134069
30    1.0  1523134100

In [10]:
for index,row in price.iterrows():
    print(row['price'].dtype)

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


In [ ]:
for index,row in price.iterrows():
    print(row['price'])

In [ ]:
price.head()

In [ ]:
price.head(30)

In [11]:
price_label = []
headlines = []

for row in price.iterrows():
    daily_headlines = []
    timestamp = row[1]['timestamp']
    price_label.append(row[1]['price'])
    for row_ in news[news.time<=timestamp].iterrows() and news[news.time>(timestamp-30)].iterrows():
        daily_headlines.append(row_[1]['text'])
    
    # Track progress
    headlines.append(daily_headlines)
    if len(price) % 500 == 0:
        print(len(price))

In [12]:
print(len(price))
print(len(headlines))

6090
6090


In [13]:
print(price.shape)
print(headlines.shape)

(6090, 2)


AttributeError: 'list' object has no attribute 'shape'

In [14]:
print(price_label[2])
print(headlines[1])

1.0
['I tested a new utility token out there - SynapseAI \r\rDecentralized AI Network -Train automation. Get paid forever.\x89Û_ https://t.co/EJVCtMQ9Y6', 'RT @SDWouters: 10 months ago #Bitcoin had 7k full nodes vs. 11k today.\rIn the same timeframe #Ethereum went from 25k full nodes to 15k.\r\rMa\x89Û_', 'bitcoin cash 32 Megabyte Block Size Increase and Op-Code Additions\r\rhttps://t.co/JAPAP9WiiQ', 'What is blockchain - the technology behind Bitcoin?  https://t.co/cS21jZrjgQ \r\r#blockchain #blockchaintechnology\x89Û_ https://t.co/EODfA86VnK', 'RT @Viking7070: Local governments are starting to understand.  https://t.co/EKpigTfev6', 'RT @Applancer_pro: Bitcoin finally opens us to new opportunities https://t.co/cvFj6vOinL via @applancer_crypt', "RT @tvtwocom: What's so special about Interactive Coin Offering? https://t.co/LQu8sPsfzR // #tvrevolution #crypto #cryptocurrencies #bitcoi\x89Û_", "@NickBakhuis @NZXT That's the very cpu I have my eye on.... Just waiting on bitcoin gaining som

In [15]:
contractions = { 
"ain't": "am not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he's": "he is",
"how'd": "how did",
"how'll": "how will",
"how's": "how is",
"i'd": "i would",
"i'll": "i will",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'll": "it will",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"must've": "must have",
"mustn't": "must not",
"needn't": "need not",
"oughtn't": "ought not",
"shan't": "shall not",
"sha'n't": "shall not",
"she'd": "she would",
"she'll": "she will",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"that'd": "that would",
"that's": "that is",
"there'd": "there had",
"there's": "there is",
"they'd": "they would",
"they'll": "they will",
"they're": "they are",
"they've": "they have",
"wasn't": "was not",
"we'd": "we would",
"we'll": "we will",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"where'd": "where did",
"where's": "where is",
"who'll": "who will",
"who's": "who is",
"won't": "will not",
"wouldn't": "would not",
"you'd": "you would",
"you'll": "you will",
"you're": "you are"
}

In [16]:
def clean_text(text, remove_stopwords = True):
    '''Remove unwanted characters and format the text to create fewer nulls word embeddings'''
    
    # Convert words to lower case
    text = text.lower()
    
    # Replace contractions with their longer forms 
    if True:
        text = text.split()
        new_text = []
        for word in text:
            if word in contractions:
                new_text.append(contractions[word])
            else:
                new_text.append(word)
        text = " ".join(new_text)
    
    # Format words and remove unwanted characters
    text = re.sub(r'&amp;', '', text) 
    text = re.sub(r'0,0', '00', text) 
    text = re.sub(r'[_"\-;%()|.,+&=*%.,!?:#@\[\]]', ' ', text)
    text = re.sub(r'\'', ' ', text)
    text = re.sub(r'\$', ' $ ', text)
    text = re.sub(r'u s ', ' united states ', text)
    text = re.sub(r'u n ', ' united nations ', text)
    text = re.sub(r'u k ', ' united kingdom ', text)
    text = re.sub(r'j k ', ' jk ', text)
    text = re.sub(r' s ', ' ', text)
    text = re.sub(r' yr ', ' year ', text)
    text = re.sub(r' l g b t ', ' lgbt ', text)
    text = re.sub(r'0km ', '0 km ', text)
    
    # Optionally, remove stop words
    if remove_stopwords:
        text = text.split()
        stops = set(stopwords.words("english"))
        text = [w for w in text if not w in stops]
        text = " ".join(text)

    return text

In [17]:
import re
from nltk.corpus import stopwords
clean_headlines = []

for daily_headlines in headlines:
    clean_daily_headlines = []
    for headline in daily_headlines:
        clean_daily_headlines.append(clean_text(headline))
    clean_headlines.append(clean_daily_headlines)

In [18]:
short_headlines = [item[:60] for item in clean_headlines]

In [19]:
def add_avg_sentiment_list(data):
	sid = SentimentIntensityAnalyzer()
	avgs = np.empty((len(data),1))
	for i in range(0,len(data)):
		sentiments=(sid.polarity_scores(str(data[i]))['compound'])
		avg = float((sentiments))/len(data[i])
		avgs[i] = avg
	print("avg")
	print(avgs)
	print(avgs.shape)
	return avgs

In [39]:
sentiment_included = add_avg_sentiment_list(short_headlines)
print("sentiment_include")
print(sentiment_included.shape)

avg
[[ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 ..., 
 [ 0.01649333]
 [ 0.01649333]
 [ 0.01651333]]
(6090, 1)
sentiment_include
(6090, 1)


In [21]:
print(sentiment_included[:100])

[[ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663   ]
 [ 0.01663833]
 [ 0.016645  ]
 [ 0.01662833]
 [ 0.01664167]
 [ 0.01661833]
 [ 0.01652167]
 [ 0.01610167]
 [ 0.016235  ]
 [ 0.01661333]
 [ 0.01660167]
 [ 0.01659   ]
 [ 0.01657667]
 [ 0.01661   ]
 [ 0.01660333]
 [ 0.01661   ]
 [ 0.01660333]
 [-0.00669833]
 [ 0.01561833]
 [ 0.01648667]
 [ 0.01659833]
 [ 0.01653833]
 [ 0.01662   ]
 [ 0.01662667]
 [ 0.01664333]
 [ 0.01662167]
 [ 0.016625  ]
 [ 0.016605  ]
 [ 0.01657667]
 [ 0.01657333]
 [ 0.01640667]
 [ 0.016605  ]
 [ 0.01662333]
 [ 0.01662167]
 [ 0.01651   ]
 [ 0.01647833]
 [ 0.01448   ]
 [ 0.01649333]
 [ 0.01653833]
 [ 0.01664333]
 [ 0.01663167]
 [ 0.01662833]
 [ 0.01663   ]
 [ 0.016635  ]
 [ 0.01661

In [22]:
print(price_label[0:10])

[0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0]


In [32]:
myList = [int(x) for x in price_label]

In [33]:
myList

[0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,


In [36]:
mylist_label = np.asarray((myList))
print(mylist_label[0:10])
print(mylist_label.shape)

[0 1 1 1 1 0 0 1 1 1]
(6090,)


In [27]:
labels = np.empty((len(price_label)))

TypeError: data type not understood

In [24]:
print(labels.shape)

(6090,)


In [25]:
astype(numpy.int64)

[  0.00000000e+000   2.02863354e-320   0.00000000e+000   4.94065646e-323
   1.34879921e-320               nan               nan               nan
   6.10465775e-261               nan]


In [24]:
def divide_train_test(data):
	train = data[:4500]
	test = data[4500:]
	return train, test

In [40]:
train_set, test_set = divide_train_test(sentiment_included)

In [47]:
print("train_set")
print(train_set.shape)

train_set
(1610, 1)


In [42]:
def divide_train_label(data):
	train = data[:4500]
	test = data[4500:]
	return train, test

In [43]:
train_label, test_label = divide_train_test(mylist_label)

In [50]:
print("train_labels")
print(train_label.shape)
print(train_label[0:30])

train_labels
(1610,)
[0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1]


In [49]:
print("test_labels")
print(test_label.shape)
print(test_label[0:])

test_labels
(4479,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [46]:
print("test_set")
print(test_set.shape)

test_set
(4479, 1)


In [51]:
def train(data, labels):
	print(data.shape)
	print(labels.shape)
	return svm.SVC(kernel='linear', C=1).fit(data, labels)

In [52]:
clsfr = train(train_set, train_label.astype('int'))
print("Training done.")

(1610, 1)
(1610,)
Training done.


In [54]:
print(clsfr)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [55]:
def cross_validate(data, labels, clsfr):
	return cross_val_score(clsfr, data, labels, cv=5)

In [61]:
results = cross_validate(test_set, test_label.astype('int'), clsfr)
print(test_label.mean())
print(results)
print("Avg = " + str(results.mean()))
print("Cross validation done.")
pred=clsfr.predict(train_set)
print("prediction shape")
print(pred.shape)
print(pred[0:])
print(train_label[0:30])

0.767805313686
[ 0.76785714  0.76785714  0.76785714  0.76785714  0.76759777]
Avg = 0.767805267358
Cross validation done.
prediction shape
(1610,)
[1 1 1 ..., 1 1 1]
[0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1]


In [ ]:
train_set[0:10]