In [13]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
# fix random seed for reproducibility
numpy.random.seed(7)
# define the raw dataset
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# create mapping of characters to integers (0-25) and the reverse
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))
# prepare the dataset of input to output pairs encoded as integers
seq_length = 3
dataX = []
dataY = []
for i in range(0, len(alphabet) - seq_length, 1):
	seq_in = alphabet[i:i + seq_length]
	seq_out = alphabet[i + seq_length]
	dataX.append([char_to_int[char] for char in seq_in])
	dataY.append(char_to_int[seq_out])
	print (seq_in, '->', seq_out)
print (len(dataX))
print (len(dataY))
dataX=numpy.reshape(dataX,(len(dataX),3))
print (dataX)
X = numpy.reshape(dataX, (len(dataX), 3, 1))
print(X)
# reshape X to be [samples, time steps, features]

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z
23
23
[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]]
[[[ 0]
  [ 1]
  [ 2]]

 [[ 1]
  [ 2]
  [ 3]]

 [[ 2]
  [ 3]
  [ 4]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 5]
  [ 6]
  [ 7]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 7]
  [ 8]
  [ 9]]

 [[ 8]
  [ 9]
  [10]]

 [[ 9]
  [10]
  [11]]

 [[10]
  [11]
  [12]]

 [[11]
  [12]
  [13]]

 [[12]
  [13]
  [14]]

 [[13]
  [14]
  [15]]

 [[14]
  [15]
  [16]]

 [[15]
  [16]
  [17]]

 [[16]
  [17]
  [18]]

 [[17]
  [18]
  [19]]

 [[18]
  [19]
  [20]]

 [[19]
  [20]
  [21]]

 [[20]
  [21]
  [22]]

 [[21]
  [22]
  [23]]

 [[2